[loggers]
keys=root,sampleLogger

[handlers]
keys=consoleHandler, fileHandler

[formatters]
keys=sampleFormatter

[logger_root]
level=WARNING
handlers=consoleHandler, fileHandler

[logger_sampleLogger]
level=DEBUG
handlers=consoleHandler
qualname=sampleLogger
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=sampleFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=handlers.RotatingFileHandler
level=DEBUG
formatter=sampleFormatter
args=('{}/logfile.log'.format(os.path.dirname(os.path.abspath(sys.modules['__main__'].__file__))), 'a', 1000000, 5)

[formatter_sampleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s